version: 1.0.{build}
os: Visual Studio 2013
platform:
  - x64
configuration:
  - Release
artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\bin\Release\WiredTigerNet.dll
  - path: %APPVEYOR_BUILD_FOLDER%\bin\Release\WiredTigerNet.pdb
